import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import{BsFillMoonStarsFill} from 'react-icons/bs';
import{AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Dimitri marco portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 " >
          <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className=' text-xl font-burtons'>
                DevelopersBoyd
              </h1>
              <ul className=' flex items-center'>
                <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl'/></li>
                <li className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'><a href='#'>Resume</a></li>
              </ul>
            </nav>


            <div className=' text-center p-10'>
              <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
                Dimetric Marco
              </h2>
              <h3 className=' text-2xl py-2 md:text-3xl'>Develover and Desainer</h3>
              <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-2-xl max-auto'>
              DESAINER Indonesia Coreta Louise ikut melenggang di ajang fashion show, New York Fashion Week. Dalam kesempatan ini, desainer dari Indonesia Now itu turut memamerkan koleksi terbarunya.
              Kali ini, Louise menghadirkan koleksi busana spesial Spring/Summer 2023, Sea Reflection, membawa fashion dari laut ke kota. Koleksi yang dibawa ke ajang tersebut terinspirasi dari keindahan alam bawah laut di Bunaken, Sulawesi Utara.
              </p>
            </div>
            <div className=' flex text-5xl justify-center gap-16 py-3 text-gray-700 '>
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mb-10 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved} layout='fill' objectFit='cover' />
            </div>
          </section>


          <section>
            <div className=''>
              <h3 className=' text-3xl py-1'>
                Servicers I offer
              </h3>
              <p className=' text-md py-5 leading-8 text-gray-800'> IT support officers provide help and advice to people and organizations <span className=' text-teal-500'> using computer </span> software or equipment. IT support officers may also be known as <span className=' text-emerald-500'>IT operations support analysts</span>, IT support technicians or help desk officers.</p>
              <p className=' text-md py-2 leading-8  text-gray-800'>You would usually work out of an office, using a phone and computer. In a large company, you might need to travel between company sites. In a smaller company, you might work with other staff at their workstations.</p>
            </div>
            <div className=' lg:flex gap-10'>
              <div className=' text-center shadow-lg pd-10 rounded-xl my-10'>
                <Image src={design} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautifully design</h3>
               <p className='py-2'>Belajar Bersama Pahrizal Dan Buat Desain Menarik Ok</p>
              <h4 className='py-2 text-teal-600'>Tools Yang saya Gunkan</h4>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>PhotoShop</p>
              <p className=' text-gray-800 py-1'>Dan Juga Ilustrator Lain nya</p>        
              </div>
              <div className=' text-center shadow-lg pd-10 rounded-xl my-10'>
                <Image src={code} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautifully design</h3>
               <p className='py-2'>Belajar Bersama Pahrizal Dan Buat Desain Menarik Ok</p>
              <h4 className='py-2 text-teal-600'>Tools Yang saya Gunkan</h4>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>PhotoShop</p>
              <p className=' text-gray-800 py-1'>Dan Juga Ilustrator Lain nya</p>        
              </div>
              <div className=' text-center shadow-lg pd-10 rounded-xl my-10'>
                <Image src={consulting} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautifully design</h3>
               <p className='py-2'>Belajar Bersama Pahrizal Dan Buat Desain Menarik Ok</p>
              <h4 className='py-2 text-teal-600'>Tools Yang saya Gunkan</h4>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>PhotoShop</p>
              <p className=' text-gray-800 py-1'>Dan Juga Ilustrator Lain nya</p>        
              </div>
            </div>
          </section>


          <section>
            <div>
              <h3 className=' text-3xl py-1'>Portofolio</h3>
              <p className=' text-md py-5 leading-8 text-gray-800'> IT support officers provide help and advice to people and organizations <span className=' text-teal-500'> using computer </span> software or equipment. IT support officers may also be known as <span className=' text-emerald-500'>IT operations support analysts</span>, IT support technicians or help desk officers.</p>
              <p className=' text-md py-2 leading-8  text-gray-800'>You would usually work out of an office, using a phone and computer. In a large company, you might need to travel between company sites. In a smaller company, you might work with other staff at their workstations.</p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1'>
                <Image src={web1} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout={'responsive'} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src={web2} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout={'responsive'} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src={web3} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout={'responsive'} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src={web4} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout={'responsive'} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src={web5} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout={'responsive'} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src={web6} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout={'responsive'} />
              </div>
              
            </div>
          
          </section>
          
      </main>


    </div>
  )
}
